version: "3"
services:

  #UTILS

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-NGINX
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-php-main
      - api-go-auth

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-POSTGRES
    container_name: pgs
    volumes:
      - ./postgres1/data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile-MIGRATE
    container_name: mgt

  #SERVICES

  api-go-auth:
    build:
      context: .
      dockerfile: Dockerfile-API-GO-AUTH
    container_name: api-go-auth
    volumes:
      - ./api-go-auth/logging/logs:/logs
    ports:
      - "11400:11400"
    depends_on:
      - postgres

  web-php-main:
    build:
      context: .
      dockerfile: Dockerfile-WEB-PHP-MAIN
    container_name: web-php-main