FROM golang:1.18 AS builder

WORKDIR /app

COPY migrate .
RUN go mod tidy
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -o app .

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/app /bin/app

COPY migrate/config.json /config.json

COPY api-go-auth/migrations /migrations/api-go-auth/

ENTRYPOINT ["/bin/app"]
