version: "3"
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - alsiberij-main

  alsiberij-main:
    build:
      context: alsiberij-main
      dockerfile: Dockerfile
    container_name: als-main