version: "3"
services:

  #UTILS

  nginx:
    build:
      context: nginx
      dockerfile: nginx/Dockerfile-NGINX
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-php-main
      - api-go-auth

  postgres:
    build:
      context: postgres
      dockerfile: postgres/Dockerfile-POSTGRES
    container_name: pgs
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  migrate:
    build:
      context: migrate
      dockerfile: migrate/Dockerfile-MIGRATE
    container_name: mgt

  #SERVICES

  api-go-auth:
    build:
      context: api-go-auth
      dockerfile: api-go-auth/Dockerfile-API-GO-AUTH
    container_name: api-go-auth
    volumes:
      - ./api-go-auth/logger/logs:/logs
    ports:
      - "11400:11400"
      - "10400:10400"
    depends_on:
      - postgres

  web-php-main:
    build:
      context: web-php-main
      dockerfile: web-php-main/Dockerfile-WEB-MAIN-PHP
    container_name: web-php-main