version: "3"
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - alsiberij-main-php

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: pgs
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  alsiberij-main-php:
    build:
      context: alsiberij-main-php
      dockerfile: Dockerfile
    container_name: als-main-php