CREATE TYPE "Role" AS ENUM ('CREATOR', 'ADMIN', 'MODERATOR', 'PRIVILEGED_USER', 'USER');
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(64) NOT NULL,
    login VARCHAR(32) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role "Role" DEFAULT 'USER' NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ON users(email);
CREATE UNIQUE INDEX ON users(login);