ALTER TABLE refresh_tokens ADD COLUMN "expiresAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE refresh_tokens ALTER COLUMN "expiresAt" DROP DEFAULT;

ALTER TABLE refresh_tokens ALTER COLUMN "lastUsedAt" DROP DEFAULT;
ALTER TABLE refresh_tokens ALTER COLUMN "lastUsedAt" DROP NOT NULL;